### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by flocsy** [ecasilla/grunt-liquibase#13]
I would like to help in adding mysql support. To add the mysql driver jar would be very easy, but not very useful. IMHO we should split out the postgresql driver to a separate node module, and make it possible for everyone to only install the modules (jars) he really uses.

I would like to hear what others think about it, especially @cgreening, are you open to some kind of solution as a pull request? If yes, what do you suggest?

**Comment by cgreening** [comment]
I can add you as a collaborator if you'd like?

**Comment by flocsy** [comment]
Sure, but what does that mean? I only worked like: forked, pushed my changes, then pull request.
Also I'd like some input in terms of how to start (I know how to do it for my needs, but I'd prefer to hear others and do it in a way that will make more people happy, at least those that use either postgresql and/or mysql, but I guess, that after the change I plan it would be easier to add later other plugins as well.

**Comment by sameetn** [comment]
if you do install postgresql as a separate module, then it would still be pulled in with the same npm i along with the mysql module right? In that case, it would probably make more sense to include both the jars and allow something through the options to control which one to use. how does that sound. That way most of the liquibase stuff can remain common just the connectivity etc. can change.

**Comment by flocsy** [comment]
This is what I did today because I needed something "quick & dirty": https://github.com/flocsy/grunt-liquibase/tree/monolitic, but I dislike it for 3 reasons:

1. why do I need to download & install the postgresql driver if I don't even have one pg server?
2. if I add both of them to the classpath in order to make it easier to select only the driver you need, then it even loads both of them if I'm not mistaken.
3. now it's 2 drivers, but next months it could be 5, and most of the people will only use 1 or maximum 2 of them, and even those 2 only one at a time...

So I would prefer as a long term solution something like:
npm i grunt-liquibase
npm i grunt-liquibase-mysql
OR npm i grunt-liquibase-postgresql

There's one serious issue with this though: it's not backwards compatible for those who already use "grunt-liquibase" with the postgresql, 'cause it won't work unless they add grunt-liquibase-postgresql plugin as well. But this is a different problem that we'll need to address after we decided how we want it to look, then we'll see how to deal with this.

**Comment by sameetn** [comment]
I see what you are saying. The pattern you are suggesting is exactly what is used by the maven-liquibase-plugin since I had to do a dependency on that as well as the DB driver I used :-)

I am fine with that approach. If you want to send in a PR, I would be happy to review it :-)

**Comment by flocsy** [comment]
Ok, I'll do it next week. Any idea how to minimize the problem for people who use postgresql? Is it enough to create a major release? (not even use what it would be in this case. Current is 0.1.11, so the next major should be 1.0.0? Or only 0.2.0?) Or make it more smooth, for example:

grunt-liquibase-core, grunt-liquibase-postgresql, grunt-liquibase-mysql?
This way grunt-liquibase would just not be updated any more, but won't break anything (and if there's a way to tell npm that the upgrade of grunt-liquibase is grunt-liquibase-postgresql, that would solve even the updates, but I'm not sure if there's such a thing in npm)

**Comment by cgreening** [comment]
I think making it a major version number change is probably the nicest thing to do to users. I think it should be 1.0.0 according to http://semver.org/ as it's a breaking change.

Alternatively we can mark the old package as deprecated with a warning message that tells users to install the core and database driver: https://docs.npmjs.com/cli/deprecate

**Comment by sameetn** [comment]
Agree with @cgreening 
>  grunt-liquibase-core, grunt-liquibase-postgresql, grunt-liquibase-mysql?
This way grunt-liquibase would just not be updated any more, but won't break anything (and if there's a way to tell npm that the upgrade of grunt-liquibase is grunt-liquibase-postgresql, that would solve even the updates, but I'm not sure if there's such a thing in npm)

I am not sure if that is even necessary since they would be separate packages, it would be up to the folks involved to use the latest if they need it, correct?

**Comment by flocsy** [comment]
Ok, here it is:
https://github.com/flocsy/grunt-liquibase
https://github.com/flocsy/grunt-liquibase-postgresql
https://www.npmjs.com/package/grunt-liquibase-postgresql
Pull request: https://github.com/cgreening/grunt-liquibase/pull/15

And the MySql driver:
https://github.com/flocsy/grunt-liquibase-mysql
I hope to publish it to npm soon.

**Comment by ecasilla** [comment]
merged
